### ISSUE TITLE
Provide feedback to the user in case of an error

### ISSUE THREAD

**Issue by centreon** [centreon/centreon-web-application-analytics#3]
---

Author Name: **Quentin Delance** (Quentin Delance)
Original Redmine Issue: 5861, https://forge.centreon.com/issues/5861
Original Date: 2014-10-07
Original Assignee: Quentin Delance

---

One of my clients wants to have an idea of the step on which the test scenario has failed.
We have designed a solution. This ticket is here to track the feature. Contact me if you want to integrate such feature.

**Comment by qdelance** [comment]
Solution is to use "echo" command in scenarios.
User can insert echo "some text" commands before one or more selenium commands.
These echo command are not directly useable by the selenium server, but plugin will keep the last one in memory and print it in case of an error. 
Doc will be updated later.
